kind: Deployment
apiVersion: apps/v1
metadata:
  name: payhub-fe
  namespace: prod
  labels:
    app: proxy-payhub-fe
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payhub-fe
      env: prod
  template:
    metadata:
      labels:
        app: payhub-fe
        env: prod
    spec:
      volumes:
        - name: payhub-fe-config
          configMap:
            name: payhub-fe-config
            items:
              - key: .env
                path: .env
        # - name: payhub-fe-key
        #   configMap:
        #     name: payhub-fe-key
        #     items:
        #       - key: .key
        #         path: .key
        - name: payhub-fe-local
          configMap:
            name: payhub-fe-local
            items:
              - key: .env.local
                path: .env.local
      containers:
        - name: payhub-fe
          image: 'images.247.or.id/pandi/payment-aggregator-frontend:latest'
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: payhub-fe-config
              mountPath: /app/.env
              subPath: .env
            # - name: payhub-fe-key
            #   mountPath: /app/.key
            #   subPath: .key
            - name: payhub-fe-local
              mountPath: /app/.env.local
              subPath: .env.local
          imagePullPolicy: Always
      restartPolicy: Always
      imagePullSecrets:
        - name: secret-prod